/**
 * Converts a MongoDB Content document into a valid siteConfig.ts string.
 * The portfolio reads this file directly — no API calls required.
 */
function generateConfig(content) {
  // Strip MongoDB internal fields
  const {
    _id, __v, createdAt, updatedAt, lastSaved, lastPublished,
    settings, // settings live only in admin, not exposed to portfolio
    ...siteData
  } = content;

  // profileImage lives inside personal — rename to match original structure
  const personal = { ...siteData.personal };
  delete personal.profileImage; // not in original siteConfig; profile photo is /profile.png

  const config = {
    personal: {
      name: personal.name || '',
      shortName: personal.shortName || '',
      initials: personal.initials || '',
      title: personal.title || '',
      tagline: personal.tagline || '',
      location: personal.location || '',
      phone: personal.phone || '',
      email: personal.email || '',
      whatsapp: personal.whatsapp || '',
      linkedin: personal.linkedin || '',
      experience: personal.experience || '3+',
      cvPath: personal.cvPath || '/cv-ashraful-alam-ashik.pdf',
    },
    hero: siteData.hero || { typewriterTexts: [], stats: [] },
    about: siteData.about || { paragraphs: [], quickStats: [] },
    experience: siteData.experience || { current: {}, previous: [] },
    certifications: (siteData.certifications || []).map(({ _id, image, ...c }) => c),
    services: (siteData.services || []).map(({ _id, ...s }) => s),
    caseStudies: (siteData.caseStudies || []).map(({ _id, ...cs }) => cs),
    skills: siteData.skills || [],
    whyWorkWithMe: (siteData.whyWorkWithMe || []).map(({ _id, ...w }) => w),
    seoProposal: siteData.seoProposal || {},
    navigation: siteData.navigation || [],
  };

  const json = JSON.stringify(config, null, 2);

  return `// Site Configuration
// Auto-generated by Admin Dashboard — ${new Date().toISOString()}
// Do NOT edit this file manually. Use the Admin Dashboard at /admin instead.

export const siteConfig = ${json};

export default siteConfig;
`;
}

module.exports = { generateConfig };
